export default [[
    {
        id: 0,
        category: 'Воробьиные',
        name: 'Сорока',
        species: 'Pica pica',
        description: 'Сороки известны страстью к блестящим вещам. Эти птицы тащат в гнездо сверкающие на солнце фантики, блестки, камушки и стеклышки. Что движет этими пернатыми в подобном коллекционировании, орнитологи сказать не могут.\n Такая дикая птица, как сорока, может стать домашним питомцем. Эти пернатые быстро привыкают к человеку, адаптируются к окружающим условиям. Вскормленные человеком, взрослые сороки узнают хозяина в лицо, становятся ручными, кормятся из рук и не улетают от него надолго.',
        imgUrl: '',
        imgTag: 'pica',
        audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/GYAUIPUVNM/XC520627-Pica pica_2020.01.12_12.31_01.mp3',
    }, {
        id: 1,
        category: 'Воробьиные',
        name: 'Грач',
        species: 'Corvus frugilegus',
        description: 'В полете благодаря обтекаемым перьям, грач развивает скорость до 85 километров в час.\nМолодой грач внешне похож на черную ворону. Отличить грачонка от вороны можно по более тонкому и прямому клюву и удлиненным, торчащим в стороны перьям на ногах и боках.',
        imgUrl: '',
        imgTag: 'frugilegus',
        audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/LELYWQKUZX/XC492941-Corvus%20frugilegus%20190528_001%2CAA.MP3',
    }, {
        id: 2,
        category: 'Воробьиные',
        name: 'Ворон',
        species: 'Corvus corax',
        description: 'Вороны – умные, осторожные птицы. Они умеют блестяще маневрировать в воздухе и ходить по земле.\nВороны ведут сложную социальную жизнь. Обучаются в течение всей жизни, легко приспосабливаются к изменениям в условиях окружающей среды. Ранней весной они создают постоянные пары, вместе строят гнезда, выращивают потомство.',
        imgUrl: '',
        imgTag: 'corax',
        audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/XIQVMQVUPP/XC518684-Grands%20corbeaux%2009012020%20Suzon.mp3',
    }, {
        id: 3,
        category: 'Воробьиные',
        name: 'Дрозд',
        species: 'Turdus philomelos',
        description: 'Дрозд — лучший певец из отряда воробьиных. Песня состоит только из красивых звучных свистов и коротких трелей. Часто ее слышно в утреннее и вечернее время. Поют в течении всего периода гнездования.',
        imgUrl: '',
        imgTag: 'philomelos',
        audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/SDPCHKOHRH/XC485904-Grive%20musicienne%20chant%202.mp3',
    }, {
        id: 4,
        category: 'Воробьиные',
        name: 'Зяблик',
        species: 'Fringilla coelebs',
        description: 'Самцы щепетильно подходят к своему отцовству. Они оберегают жилище, оповещают, если рядом появился хищник. Кроме того, самцы помогают выкормить даже чужих птенцов.',
        imgUrl: '',
        imgTag: 'coelebs',
        audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/JCPKCBKKAQ/XC513035-FRICOE_170605_3108_NDDL44_Freneliere.mp3',
    }, {
        id: 5,
        category: 'Воробьиные',
        name: 'Сойка',
        species: 'Garrulus glandarius',
        description: 'Самцы щепетильно подходят к своему отцовству. Они оберегают жилище, оповещают, если рядом появился хищник. Кроме того, самцы помогают выкормить даже чужих птенцов.',
        imgUrl: '',
        imgTag: 'glandarius',
        audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/SNRCANJSRX/XC460049-Garrulus%20glandarius%20call%20V%C3%A4stersj%C3%B6n%20111014%20aNR.mp3',
    },
    ]]