export default [[
    {
        id: 0,
        category: 'Воробьиные',
        name: 'Сорока',
        species: 'Pica pica',
        description: 'Такая дикая птица, как сорока, может стать домашним питомцем. Эти пернатые быстро привыкают к человеку, адаптируются к окружающим условиям. Вскормленные человеком, взрослые сороки узнают хозяина в лицо, становятся ручными, кормятся из рук и не улетают от него надолго.',
        imgUrl: '',
        imgTag: 'pica',
        audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/GYAUIPUVNM/XC520627-Pica pica_2020.01.12_12.31_01.mp3',
    }, {
        id: 1,
        category: 'Воробьиные',
        name: 'Грач',
        species: 'Corvus frugilegus',
        description: 'В полете благодаря обтекаемым перьям, грач развивает скорость до 85 километров в час.\nМолодой грач внешне похож на черную ворону. Отличить грачонка от вороны можно по более тонкому и прямому клюву и удлиненным, торчащим в стороны перьям на ногах и боках.',
        imgUrl: '',
        imgTag: 'frugilegus',
        audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/LELYWQKUZX/XC492941-Corvus%20frugilegus%20190528_001%2CAA.MP3',
    }, {
        id: 2,
        category: 'Воробьиные',
        name: 'Ворон',
        species: 'Corvus corax',
        description: 'Вороны – умные, осторожные птицы. Они умеют блестяще маневрировать в воздухе и ходить по земле.\nВороны ведут сложную социальную жизнь. Обучаются в течение всей жизни, легко приспосабливаются к изменениям в условиях окружающей среды.',
        imgUrl: '',
        imgTag: 'corax',
        audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/XIQVMQVUPP/XC518684-Grands%20corbeaux%2009012020%20Suzon.mp3',
    }, {
        id: 3,
        category: 'Воробьиные',
        name: 'Дрозд',
        species: 'Turdus philomelos',
        description: 'Дрозд — лучший певец из отряда воробьиных. Песня состоит только из красивых звучных свистов и коротких трелей. Часто ее слышно в утреннее и вечернее время. Поют в течении всего периода гнездования.',
        imgUrl: '',
        imgTag: 'philomelos',
        audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/SDPCHKOHRH/XC485904-Grive%20musicienne%20chant%202.mp3',
    }, {
        id: 4,
        category: 'Воробьиные',
        name: 'Зяблик',
        species: 'Fringilla coelebs',
        description: 'Самцы щепетильно подходят к своему отцовству. Они оберегают жилище, оповещают, если рядом появился хищник. Кроме того, самцы помогают выкормить даже чужих птенцов.',
        imgUrl: '',
        imgTag: 'coelebs',
        audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/JCPKCBKKAQ/XC513035-FRICOE_170605_3108_NDDL44_Freneliere.mp3',
    }, {
        id: 5,
        category: 'Воробьиные',
        name: 'Сойка',
        species: 'Garrulus glandarius',
        description: 'Самцы щепетильно подходят к своему отцовству. Они оберегают жилище, оповещают, если рядом появился хищник. Кроме того, самцы помогают выкормить даже чужих птенцов.',
        imgUrl: '',
        imgTag: 'glandarius',
        audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/SNRCANJSRX/XC460049-Garrulus%20glandarius%20call%20V%C3%A4stersj%C3%B6n%20111014%20aNR.mp3',
    },
    ], [
        {
            id: 0,
            category: 'Домашние',
            name: 'Утка',
            species: 'Anas platyrhynchos',
            description: 'Селезни не умеют крякать, а кряканье самочек уток не имеет эха. \nНоворожденные утята принимают за мать первое существо, которое увидят при появлении на свет.\nУтиные лапы отличаются отсутствием нервных окончаний, благодаря чему птицы могут ходить даже по льду и снегу.',
            imgUrl: '',
            imgTag: 'platyrhynchos',
            audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/LELYWQKUZX/XC234891-%20150403_002%2C3.04.2015%2C%20%D1%80.%20%D0%98%D0%BB%D0%B5%D1%82%D1%8C%2C%D0%A1.MP3',
        }, {
            id: 1,
            category: 'Домашние',
            name: 'Цесарка',
            species: 'Numida meleagris',
            description: 'Цесарки довольно быстро привыкают к людям, которые за ними ухаживают, а при виде посторонних поднимают жуткий шум, и поэтому наравне с гусями являются хорошими сторожами.\nЦесарок можно приучить поедать колорадских жуков, добавляя вредителей птицам в пищу. Привыкнув к такому прикорму, цесарка сама начинает искать насекомых и может стать помощником в борьбе с ними.',
            imgUrl: '',
            imgTag: 'meleagris',
            audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/GQMCPIVNXX/XC507927-Helmeted%20Guineafowl.mp3',
        }, {
            id: 2,
            category: 'Домашние',
            name: 'Петух',
            species: 'Gallus gallus domesticus',
            description: 'На одного петуха в стае должно приходиться от 8 до 12 курочек. Уже в 6 месяцев самки могут нести первые яйца, и эта способность сохраняется у них до 10 лет. В то время как петуха используют только 2-3 года.',
            imgUrl: '',
            imgTag: 'gallus',
            audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/QZIUOAQAMG/XC205483-para%20xeno%20canto.mp3',
        }, {
            id: 3,
            category: 'Домашние',
            name: 'Курица',
            species: 'Gallus gallus domesticus',
            description: 'Пищевые яйца курицы могут нести и без петуха.',
            imgUrl: '',
            imgTag: 'gallus-domesticus',
            audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/QZIUOAQAMG/XC205483-para%20xeno%20canto.mp3',
        }, {
            id: 4,
            category: 'Домашние',
            name: 'Перепел',
            species: 'Coturnix coturnix',
            description: 'Птица хороша тем, что не требует отдельного помещения – 50 перепелов легко размещаются в клетке на 1 м2 площади. При этом за день они могут снести около 50 яиц весом 10 г, что соответствует практически десятку куриных яиц.',
            imgUrl: '',
            imgTag: 'coturnix',
            audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/EJIITXAJNY/XC497282-Kwartel%20190720%20Wezelse%20heide.mp3',
        }, {
            id: 5,
            category: 'Домашние',
            name: 'Страус',
            species: 'Struthio camelus',
            description: 'Птица хороша тем, что не требует отдельного помещения – 50 перепелов легко размещаются в клетке на 1 м2 площади. При этом за день они могут снести около 50 яиц весом 10 г, что соответствует практически десятку куриных яиц.',
            imgUrl: '',
            imgTag: 'struthio-camelus',
            audioUrl: 'https://www.xeno-canto.org/sounds/uploaded/YTUXOCTUEM/XC516153-Struthio_camelus_australis-FL%20quiet%20calls%20imm%20Polokwane%20GameRes%2030Oct19%208.05am%20LS115271a.mp3',
        }
    ]]